### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by martab0** [DocWizard/markdown-cwiczenia#2]
Świetnie! Jest wszystko co było na zajęciach plus trochę więcej :-)

Co można wypróbować (spoza programu zajęć):
- odsyłacz z widocznym explicite adresem HTML,
- obrazek z "dymkiem",
- wzory matematyczne - inny sposób zapisu dla odróżnienia od kodu,
- wyrównanie tekstu w tabeli do prawej, do lewej, centralnie.

**Comment by DocWizard** [comment]
Dziękuję, popróbuję :)
